name: PermissionsSetup
description: Properly set up permissions for plugins that just don't do it right.
version: "${project.version}"
author: Jikoo
main: com.github.jikoo.permissionssetup.PermissionsSetup
api-version: "1.13"
